language: node_js
node_js:
- '4.2'
deploy:
  api_key:
    secure: t2YdPtnqbxh+zTDgm7yp0eNVx+rhRUsRPXfvI/+k0iXTI9Hom4mwWjoSCqSPLSKM79G5Td6XW/iluwXIAqgSInhcRV6Sy+Z1q6btS7jjJxQYBaTlJSpih/9Xv2FJu/3sanojqFVRMwNQe+8p89WYQxdLh3qEWhnqLxHba8g67ZWsBRb4C0P8FB7Fd5ILp5sxzN8GQp2EiV846esfTnvItgm0vePqeCdKRYBo9kLK1QXEy+CoEievuyPWbMASyPJQ4gQ2u4TksquMHD19Qz6dpdNVt0P0qPpI0CZ36Od5U203omr4ONiVoEgP7YgHu3pwq9Acrk7QzSCC7k+HT2vNW3klyJroLRVgsxr6iAs1Yh3V8K6Aku6Sa3FSqwNooSMPcCr9SSzoD9v+ke4lDDy2y1eKuzOFsQL5nz0+eC9kaBt55TG+gDjIXU5LJz4vDIoW0IRp9E23+qBqeMV5d/uA7lVyKlBrGxuWEEjXUAo/Gm644kDMZUb6knr9UxJAHRb5nNfs745WIFdxhGWr93ImH4QN/PONTRtRFnLqOsM0YWqTZw4uZcOmPzFqmYXPcEZ8anlEXLlVzIw8J1PblSVHbhQ8GqC1+SMUwCycVzCx4aPaQCwCRutzJGM1s8FXToyIMcSgxw3+ZBfYVpDqBuqCugb85m/+HAAPSFYOQtBbQ1E=
  provider: heroku
  skip_cleanup: true